Condominios/Controllers/EventosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Condominios.BLL.Models;
using Condominios.DAL;
using Condominios.DAL.Interface;

namespace Condominios.Controllers
{
    public class EventosController : Controller
    {
        private readonly IEventoRepositorio _eventoRepositorio;
        private readonly IUsuarioRepositorio _usuarioRepositorio;

        public EventosController(IEventoRepositorio eventoRepositorio, IUsuarioRepositorio usuarioRepositorio)
        {
            _eventoRepositorio = eventoRepositorio;
            _usuarioRepositorio = usuarioRepositorio;
        }

        // GET: Eventos
        public async Task<IActionResult> Index()
        {
            Usuario usuario = await _usuarioRepositorio.PegarUsuarioPeloNome(User);

            if (await _usuarioRepositorio.VerificarSeUsuarioEstaEmFuncao(usuario, "Morador"))
            {
                return View(await _eventoRepositorio.PegarEventosPeloId(usuario.Id));
            }
            return View(await _eventoRepositorio.PegarTodos());
        }

        [HttpGet]
        public async Task<IActionResult> Create()
        {
            Usuario usuario = await _usuarioRepositorio.PegarUsuarioPeloNome(User);
            Evento evento = new Evento
            {
                UsuarioId = usuario.Id
            };

            return View(evento);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("EventoId,Nome,Data,UsuarioId")] Evento evento)
        {
            if (ModelState.IsValid)
            {
                await _eventoRepositorio.Inserir(evento);
                TempData["NovoRegistro"] = $"Evento {evento.Nome} inserido com sucesso";
                return RedirectToAction(nameof(Index));
            }

            return View(evento);
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            Evento evento = await _eventoRepositorio.PegarPeloId(id);
            if (evento == null)
            {
                return NotFound();
            }

            return View(evento);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("EventoId,Nome,Data,UsuarioId")] Evento evento)
        {
            if (id != evento.EventoId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                await _eventoRepositorio.Atualizar(evento);
                TempData["Atualizacao"] = $"Evento {evento.Nome} atualizado";
                return RedirectToAction(nameof(Index));
            }

            return View(evento);
        }


        [HttpPost]
        public async Task<JsonResult> Delete(int id)
        {
            await _eventoRepositorio.Excluir(id);
            TempData["Exclusao"] = $"Evento excluído";
            return Json("Evento excluído");
        }
    }
}

Condominios/Views/Eventos/Create.cshtml
@model Condominios.BLL.Models.Evento

@{ ViewData["Title"] = "Novo evento"; }

<div class="formulario">
    <div class="collection with-header">
        <form asp-action="Create">
            <div class="collection-header green darken-3">
                <h6 class="white-text">Novo evento</h6>
            </div>

            <div class="collection-item">
                <div asp-validation-summary="ModelOnly" class="red-text text-darken-4"></div>

                <div class="row">
                    <div class="input-field col s12">
                        <input asp-for="Nome" class="validate" id="nome" />
                        <label asp-for="Nome" id="nome"></label>
                        <span class="red-text text-darken-4" asp-validation-for="Nome"></span>
                    </div>
                </div>

                <div class="row">
                    <div class="input-field col s12">
                        <input asp-for="Data" type="text" class="validate" id="data" />
                        <label asp-for="Data" id="data"></label>
                        <span class="red-text text-darken-4" asp-validation-for="Data"></span>
                    </div>
                </div>

                <input type="hidden" asp-for="UsuarioId" />
            </div>

            <div class="collection-item">
                <button type="submit" class="btn-small green darken-3">Salvar</button> &emsp;
                <a asp-action="Index" asp-controller="Eventos">Voltar</a>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    <script src="~/js/InicializarDatepicker.min.js"></script>
}

Condominios/Views/Eventos/Edit.cshtml
@model Condominios.BLL.Models.Evento

@{ ViewData["Title"] = "Atualizar evento"; }

<div class="formulario">
    <div class="collection with-header">
        <form asp-action="Edit">
            <div class="collection-header blue darken-3">
                <h6 class="white-text">Atualizar evento</h6>
            </div>

            <div class="collection-item">
                <div asp-validation-summary="ModelOnly" class="red-text text-darken-4"></div>

                <input type="hidden" asp-for="EventoId" />

                <div class="row">
                    <div class="input-field col s12">
                        <input asp-for="Nome" class="validate" id="nome" />
                        <label asp-for="Nome" id="nome"></label>
                        <span class="red-text text-darken-4" asp-validation-for="Nome"></span>
                    </div>
                </div>

                <div class="row">
                    <div class="input-field col s12">
                        <input asp-for="Data" type="text" class="validate" id="data" />
                        <label asp-for="Data" id="data"></label>
                        <span class="red-text text-darken-4" asp-validation-for="Data"></span>
                    </div>
                </div>

                <input type="hidden" asp-for="UsuarioId" />
            </div>

            <div class="collection-item">
                <button type="submit" class="btn-small blue darken-3">Atualizar</button> &emsp;
                <a asp-action="Index" asp-controller="Eventos">Voltar</a>
            </div>
        </form>
    </div>
</div>




@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    <script src="~/js/InicializarDatepicker.min.js"></script>
}

Condominios/Views/Eventos/Index.cshtml
@model IEnumerable<Condominios.BLL.Models.Evento>

@{ ViewData["Title"] = "Eventos cadastrados";
                string controller = this.ViewContext.RouteData.Values["controller"].ToString(); }

<div class="tabelas">

    <partial name="_Confirmacoes" />

    <div class="collection with-header">
        <div class="collection-header grey darken-1">
            <div class="row">
                <div class="col s10">
                    <h6 class="white-text">Eventos Cadastrados</h6>
                </div>
                <div class="col s2">
                    <a asp-controller="Eventos" asp-action="Create" class="waves-effect waves-light btn-small btn-floating grey darken-4 tooltip" data-position="right" data-tooltip="Novo evento">
                        <i class="material-icons">add</i>
                    </a>
                </div>
            </div>
        </div>

        <div class="collection-item">
            <table class="striped highlight reponsive">
                <thead>
                    <tr>
                        <th>
                            @Html.DisplayNameFor(model => model.Nome)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Data)
                        </th>
                        <th>Ações</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Nome)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Data)
            </td>
            <td>
                <a asp-controller="Eventos" asp-action="Edit" asp-route-id="@item.EventoId" class="btn-floating btn-small blue darken-4 tooltip" data-position="right" data-tooltip="Atualizar evento">
                    <i class="material-icons">mode_edit</i>
                </a>

                <a onclick="ConfirmarExclusao(@item.EventoId, '@item.Nome', '@controller')" class="btn-floating btn-small red darken-4 tooltip modal-trigger" data-target="modal" data-position="right" data-tooltip="Excluir evento">
                    <i class="material-icons">delete_forever</i>
                </a>
            </td>
        </tr>}
                </tbody>
            </table>
        </div>
    </div>
</div>

<partial name="_ModalExcluir" />

@section Scripts {
    <script src="~/js/ConfirmarExclusao.min.js"></script>
}